# Generated by Django 5.0.6 on 2024-07-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('items', models.CharField(max_length=255)),
                ('items_numbering', models.IntegerField()),
                ('quantity_of_items', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
